mamar_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('transiction/', include('transiction.urls')),
]

transiction/urls.py
from django.urls import path
from .views import DepositMoneyView, WithdrawMoneyView, TransactionReportView,LoanRequestView,LoanListView,PayLoanView,TransferBalance


# app_name = 'transactions'
urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionReportView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("loan_request/", LoanRequestView.as_view(), name="loan_request"),
    path("loans/", LoanListView.as_view(), name="loan_list"),
    path("loans/<int:loan_id>/", PayLoanView.as_view(), name="pay"),
    path("transfer/", TransferBalance.as_view(), name="transfer"),
]

transiction/models.py
from django.db import models
from accounts.models import UserBankAccount
# Create your models here.
from .constants import TRANSACTION_TYPE

class Transaction(models.Model): 
    account = models.ForeignKey(UserBankAccount, related_name = 'transactions', on_delete = models.CASCADE) #ekjon user er multiple transactions hote pare jemon, se loan nibe abr withdraw korbe abr deposite korbe bla bla. 
    amount = models.DecimalField(decimal_places=2, max_digits = 12) #how much ammount he will transiction.
    balance_after_transaction = models.DecimalField(decimal_places=2, max_digits = 12)#transiction complete howar pore account e koto taka balance thaklo
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null = True) #kon dhoroner transiction korbe user, eta ki withdraw naki eta deposite kon type er transiction eta. 
    timestamp = models.DateTimeField(auto_now_add=True) #transiction er somoy ta.
    loan_approve = models.BooleanField(default=False) #loan nile oita back end theke approve korar jonne eita use kortesi 
    
    
    class Meta:
        ordering = ['timestamp'] #ei class ta ekhane use kora hoiche uporer transiction class er sathe extra charecteristics add korar jonne. jemon ekhane timestamp er vittite sokol transiction ke sort korlam. ordering ta sort korar jonne use hoi built in vabei. 

class BankCrupt(models.Model):
    is_bankcrupt = models.BooleanField(default=False, null=True, blank=True)
    

transiction/forms.py
from django import forms
from .models import Transaction
class TransactionForm(forms.ModelForm):
    #This inner class provides information about the model that the form is linked to.
    class Meta:
        #This specifies that the form works with the Transaction model.
        model = Transaction
        #This lists the fields from the Transaction model that should be included in the form.
        fields = [
            'amount',
            'transaction_type'
        ]
    #The __init__ method is indeed called when a new instance of the TransactionForm class is created. This happens whenever you create a form object to use
    def __init__(self, *args, **kwargs): # '**'kwarg takes any number of keyword arguments and creates a dictionary accessible within the function.
        self.account = kwargs.pop('account') # account value ke pop kore anlam
        super().__init__(*args, **kwargs)
        self.fields['transaction_type'].disabled = True # ei field disable thakbe
        self.fields['transaction_type'].widget = forms.HiddenInput() # user er theke hide kora thakbe
    
    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()

class DepositForm(TransactionForm):
    def clean_amount(self): # amount field ke filter korbo
        min_deposit_amount = 100
        amount = self.cleaned_data.get('amount') # user er fill up kora form theke amra amount field er value ke niye aslam, 50
        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f'You need to deposit at least {min_deposit_amount} $'
            )

        return amount

class WithdrawForm(TransactionForm):
    def clean_amount(self):
        account = self.account
        min_withdraw_amount = 500
        max_withdraw_amount = 20000
        balance = account.balance # 1000
        amount = self.cleaned_data.get('amount')
        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at least {min_withdraw_amount} $'
            )

        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at most {max_withdraw_amount} $'
            )

        if amount > balance: # amount = 5000, tar balance ache 200
            raise forms.ValidationError(
                f'You have {balance} $ in your account. '
                'You can not withdraw more than your account balance'
            )

        return amount

class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        return amount

class TransferMoneyForm(forms.Form):
    amount = forms.DecimalField()
    to_user_id = forms.IntegerField()

transiction/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import CreateView, ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from . models import Transaction, UserBankAccount, BankCrupt
from .forms import DepositForm, WithdrawForm, TransferMoneyForm
from .constants import DEPOSIT, WITHDRAWAL, LOAN, LOAN_PAID, TRANSFER, RECEIVED
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
from django.db.models import Sum
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string


def send_transaction_email(user, amount, mail_subject, template):
    message = render_to_string(template,{
        'user' : user,
        'amount' : amount
    })
    send_email = EmailMultiAlternatives(mail_subject, '', to=[user.email])
    send_email.attach_alternative(message, "text/html") 
    send_email.send()


# we use class based view, create view. 
#amra ei class take prottekbar inherit kore withdraw, loan, deposite sob gula kaj korbo
class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    model = Transaction
    template_name = 'transaction_from.html'
    title = ''
    success_url = reverse_lazy('transaction_report') # reverse_lazy use kori jokhn amra ei url theke oi url e jabo tokhn loading time komanor jonne. 

    # jokhon kono form create hobe sekhane ekta constructor call hobe setar moddhe ami ekta account use korchi jeta jei user login thakbe tar account, and sei account ta ami ekhan theke evabe pathai dilam.
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account' : self.request.user.account,
        })
        return kwargs
    
    # buit in vabe class e ekta context thake oitake override kortesi and update kortechi ekta title diya
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title' : self.title
        })
        return context

class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposite'

    def get_initial(self):
         initial = {'transaction_type' : DEPOSIT}
         return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance += amount 
        account.save(
            update_fields = ['balance']
        )
        messages.success(self.request, f'{amount}$ is deposited successfully')

        send_transaction_email(self.request.user, amount, 'Deposite message', 'deposite_email.html')

        return super().form_valid(form)
    
class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw'

    def get_initial(self):
         initial = {'transaction_type' : WITHDRAWAL}
         return initial
    def form_valid(self, form):
        try:
            obj = BankCrupt.objects.get(is_bankcrupt=True)
            messages.warning(self.request,'BANKCRUPT!!!!') 
        except BankCrupt.DoesNotExist:
            amount = form.cleaned_data.get('amount')
            account = self.request.user.account
            account.balance -= amount 
            account.save(
                update_fields = ['balance']
            )
            messages.success(self.request, f'{amount}$ withdrawn successfully')
            send_transaction_email(self.request.user, amount, 'Withdrawal message', 'withdraw_email.html')

        return super().form_valid(form)
    
class LoanRequestView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Request For Loan'

    def get_initial(self):
         initial = {'transaction_type' : LOAN}
         return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        current_loan_count = Transaction.objects.filter(account=self.request.user.account, transaction_type=LOAN, loan_approve=True).count()

        if current_loan_count>=3:
            return HttpResponse('You crossed the limitations for request')
        
        messages.success(self.request, f'Loan request {amount}$ send to your admin')

        send_transaction_email(self.request.user, amount, 'Request for a loan', 'loan_email.html')

        return super().form_valid(form)

#we are using ListView karon amader transaction report ta list akare dekhabe ekta.
class TransactionReportView(LoginRequiredMixin, ListView):
    template_name = 'transaction_report.html'
    model = Transaction
    balance = 0
    #context_object_name = 'repost_list' #eitake dhore loop chaliye repost er sob information pawa jabe, othoba chaile object_list likheo pawa jabe, amra object_list use kortesi jeta build in.

    #report er moddhe date time onujai filter korte amra 'GET' request kori, and ei date gula url e chole jai and amra ekhan theke dhori otake. etkae query kora bole. or jonne ei method ta:
    def get_queryset(self):

        # jodi user kono rokom filter use na kore date time diye tahole ekhane user er all transaction report dekhabo
        queryset = super().get_queryset().filter(
            account = self.request.user.account
        )

        start_date_str = self.request.GET.get('start_date')
        end_date_str = self.request.GET.get('end_date')

        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()
            queryset = queryset.filter(timestamp__date__gte=start_date, timestamp__date__lte=end_date)
             
            self.balance = Transaction.objects.filter(timestamp__date__gte=start_date, timestamp__date__lte=end_date).aggregate(Sum('amount'))['amount__sum']
        else:
            self.balance = self.request.user.account.balance
        return queryset.distinct()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account' : self.request.user.account
        })
        return context

# ekhane ListVew othoba DetailsView er kono kaj nai, just user loan ta korbe so ei khane amra View take user korlam. 
class PayLoanView(LoginRequiredMixin,View ):
    def get(self, request, loan_id):
        loan = get_object_or_404(Transaction, id=loan_id)

        if loan.loan_approve:
            user_account = loan.account
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.transaction_type =LOAN_PAID
                loan.save()
                return redirect('loan_list')
            else:
                messages.error(self.request, f'Loan amount is grater than available balance')
                return redirect('loan_list')

class LoanListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'loan_request.html'
    context_object_name = 'loans'

    def get_queryset(self):
        user_account = self.request.user.account
        queryset = Transaction.objects.filter(account = user_account, transaction_type =  LOAN)
        return queryset
    
class TransferBalance(LoginRequiredMixin, View):
    template_name = 'transfer_balance.html'
    success_url = reverse_lazy('transaction_report')

    def get(self, request):
        form = TransferMoneyForm()
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        form = TransferMoneyForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            to_user_id = form.cleaned_data['to_user_id']
            current_user = self.request.user.account
            try:
                to_user = UserBankAccount.objects.get(account_no=to_user_id)
                if current_user.balance >= amount:  
                    current_user.balance -= amount  
                    to_user.balance += amount       
                    current_user.save()
                    to_user.save()
                    messages.success(self.request, 'Success!')
                    send_transaction_email(self.request.user, amount, 'Transfered Balance', 'transfer_balance_email.html')
                    send_transaction_email(to_user.user, amount, 'Received Balance', 'receive_balance_email.html')
                else:
                    messages.error(self.request, 'Insufficient balance!')
            except UserBankAccount.DoesNotExist:
                messages.error(self.request, 'Acount number invalid!')

            Transaction.objects.create(
                account = current_user,
                amount = amount,
                balance_after_transaction = current_user.balance,
                transaction_type = TRANSFER,
            )
            Transaction.objects.create(
                account = to_user,
                amount = amount,
                balance_after_transaction = current_user.balance,
                transaction_type = RECEIVED,
            )
        return redirect('transfer')

transiction/templates/admin_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>
<h2>Congratulations, your loan request has been approaved!</h2>
<p>Your account {{amount}} Tk loan granted. After getting the loan your balance is {{user.account.balance}} </p>
<p>Stay with us</p>
<h5>Thank you, Mamar Bank</h5>

transiction/templates/deposite_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>
<p>Your deposite {{amount}}$ has been deposited successfully. After deposite your balance is {{user.account.balance}}</p>
<p>Stay with us</p>
<h5>Thank you, Mamar Bank</h5>

transiction/templates/loan_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>
<p>Your account request for a loan: {{amount}} Tk successfully. After admin approval this balance will be added to your balance</p>
<p>Stay with us</p>
<h5>Thank you, Mamar Bank</h5>

transiction/templates/loan_request.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 
{% block content %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Loan Report</h1>
  <hr />
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">LOAN ID</th>
        <th class="px-4 py-2">Loan Amount</th>
        <th class="px-4 py-2">Loan Approved</th>
        <th class="px-4 py-2">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for loan in loans %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
         {{ loan.id }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm text-green-700 bg-green-100"
          >
            {{ loan.amount }}
          </span>
        </td>
        <td class="px-4 py-2">
          {{ loan.loan_approve }}
        </td>
        <td class="px-4 py-2">
          {% if loan.loan_approve %}
          <a class="font-bold bg-red-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" href='{% url "pay" loan.id %}'>Pay</a>
          {% else %}
          <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

transiction/templates/receive_balance_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>
<p>Your account {{amount}} Tk has been received successfully. After received your balance is {{user.account.balance}}</p>
<p>Stay with us</p>
<h5>Thank you, Mamar Bank</h5>

transiction/templates/transaction_from.html
{% extends 'base.html' %}

{% block head_title %}
{{ title }}
{% endblock %}

{% block content %}
<div class="w-full flex mt-5 justify-center ">
    <div class="bg-white w-5/12 rounded-lg">
        {% if title == 'Request For Loan' %}
    <div><a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{% url 'loan_list' %}">View All Loan List</a></div>
        {% endif %}
        <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                    Amount
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            {% if form.amount.errors %} {% for error in form.amount.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %} {% endif %}
            <div class="flex w-full justify-center">
                <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">
                Submit
            </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

transiction/templates/transaction_report.html
{% extends 'base.html' %} 
{% load static %}
{% load humanize %}
{% block head_title %} Transaction Report{% endblock %} 

{% block content %}

<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'transaction_report' %}">
    <div class="flex justify-center">
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2"
      >
        <label for="start_date">From:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="start_date"
          name="start_date"
        />
      </div>
 
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12"
      >
        <label for="end_date">To:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="end_date"
          name="end_date"
        />
      </div>
      <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
        <button
          class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          type="submit"
        >
          Filter
        </button>
      </div>
    </div>
  </form>
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in object_list %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-red-700 bg-red-100 {% else %} text-green-700 bg-green-100 {% endif %}"
          >
            {{ transaction.get_transaction_type_display}}
          </span>
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.amount|floatformat:2|intcomma }}
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}
        </td>
      </tr>
      {% endfor %}
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
        <th class="px-4 py-2 text-left">
          $ {{ account.balance|floatformat:2|intcomma }}
        </th>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

transiction/templates/transfer_balance.html
{% extends 'base.html' %}

{% block head_title %}
Transfer Balance
{% endblock %}

{% block content %}
<div class="w-full flex mt-5 justify-center ">
    <div class="bg-white w-5/12 rounded-lg">
        <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">Transfer Balance</h1>
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                    Amount
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="to_user_id">
                    To user id
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="to_user_id" id="to_user_id" type="number" required placeholder="User account no">
            </div>
            {% if form.amount.errors %} {% for error in form.amount.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %} {% endif %}
            <div class="flex w-full justify-center">
                <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">
                Submit
            </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

transiction/templates/transfer_balance_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>
<p>Your account {{amount}} Tk has been transferd successfully. After transferd your balance is {{user.account.balance}}</p>
<p>Stay with us</p>
<h5>Thank you, Mamar Bank</h5>

transiction/templates/withdraw_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>
<p>Your account {{amount}} Tk has been withdrawn successfully. After withdrawn your balance is {{user.account.balance}}</p>
<p>Stay with us</p>
<h5>Thank you, Mamar Bank</h5>